Support more modes for running the dev server (GSI-1233)
ghga-de/data-portal pull request #28
Opened 2024-12-18 16:19 UTC by Cito

This PR makes the `run.js` script a bit more flexible. Besides running the production server, it can now run the dev server in four different modes:
- with mock API and fake authentication
- with real backend, but fake authentication
- with real OIDC provider, but mock backend
- with real backend and OIDC provider

The dev server is activated by passing the `--dev` option. The `dev_launcher` script calls the `run.js` script with this option, while passing on any other options.

See also the update documentation in the README file.

2024-12-20 18:03 UTC, ac-jorellanaf requested changes
Everything but `--with-oidc` alone works. It tries to use the localhost instead of the correct staging host. Everything else works well

2024-12-20 18:31 UTC, Cito commented
> Everything but `--with-oidc` alone works. It tries to use the localhost instead of the correct staging host.

It works for me. The env variable `data_portal_base_url` should not be set or set to `https://data.staging.ghga.dev` when testing. When I browse to https://data.staging.ghga.dev, I can login via LS Login, but the summary data is mocked.

2025-01-07 08:40 UTC, ac-jorellanaf commented
It works with the `data_portal_base_url` variable set to staging, but does not work when just unset.

2025-01-07 20:04 UTC, ac-jorellanaf approved these changes

2025-01-08 06:47 UTC, merged